### ISSUE TITLE
Component loadcore_agent-dn timeout

### ISSUE THREAD

**Issue by CarlosAndreo** [6G-SANDBOX/6G-Library#68]
# Observations

When try to deploy a `loadcore_agent-dn` component the `TASK [Create new user for experimenter access]` task get a timeout error.

## Jenkins error

```bash
TASK [Create new user for experimenter access] *********************************
Monday 25 November 2024  12:42:20 +0000 (0:00:01.039)       0:00:52.653 ******* 
fatal: [vm_kvm]: FAILED! => 
  msg: 'Timeout (12s) waiting for privilege escalation prompt: '
```

## 6G-SANDBOX-SITES

`uma`

## 6G-Library branch

`develop`

## Trial network descriptor

```yaml
trial_network:

  tn_init:
    type: "tn_init"
    dependencies: []
    input: {}
  vnet-randn:
    type: "vnet"
    name: "randn"
    dependencies:
      - "tn_init"
    input:
      one_vnet_first_ip: "10.10.10.1"
      one_vnet_netmask: "255.255.255.0"
      one_vnet_address_size: 254
      one_vnet_gw: "10.10.10.1"
      one_vnet_dns: "1.1.1.1"
  open5gs_vm-core:
    type: open5gs_vm
    name: core
    dependencies:
      - tn_init
      - vnet-randn
    input:
      one_open5gs_vm_size: "small"
      one_open5gs_vm_networks:
        - tn_vxlan
        - vnet-randn
      one_open5gs_vm_ue_subnet: "10.45.0.0/16"
      one_open5gs_vm_mcc: "001"
      one_open5gs_vm_mnc: "01"
      one_open5gs_vm_msin: "0000000001"
      one_open5gs_vm_key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      one_open5gs_vm_opc: "E8ED289DEBA952E4283B54E88E6183CA"
      one_open5gs_vm_apn: "internet"
      one_open5gs_vm_tac: 200
      one_open5gs_vm_s_nssai_sst: 1
      one_open5gs_vm_s_nssai_sd: "000001"
      one_open5gs_vm_amf_ip: "10.10.10.200"
      one_open5gs_vm_upf_ip: "10.10.10.201"
      one_open5gs_vm_ue_count: 20
  loadcore_agent-dn:
    type: "loadcore_agent"
    name: "dn"
    input:
      one_loadcore_agent_networks:
        - "tn_vxlan"
        - "vnet-randn"
        - "vnet-randn"
  loadcore_agent-gnb:
    type: "loadcore_agent"
    name: "gnb"
    input:
      one_loadcore_agent_networks:
        - "tn_vxlan"
        - "vnet-randn"
        - "vnet-randn"
        - "vnet-randn"
```
