### ISSUE TITLE
Component open5gs_vm assign one_open5gs_vm_amf_ip and one_open5gs_vm_upf_ip address ips

### ISSUE THREAD

**Issue by CarlosAndreo** [6G-SANDBOX/6G-Library#69]
# Observation

The fields indicated in the input of a descriptor file are the fields that can be modified. Therefore, in the `open5gs_vm` component, the fields `one_open5gs_vm_amf_ip` and `one_open5gs_vm_upf_ip` should allow the selection of desired values within the network range.

Currently, their behavior is different. Although they are input fields, the value is set automatically, which does not make sense.

Given the [descriptor](https://github.com/6G-SANDBOX/TNLCM/blob/develop/tn_template_lib/loadcore_open5gs_vm.yaml):

```yaml
trial_network:

  tn_init:
    type: "tn_init"
    dependencies: []
    input: {}
  vnet-randn:
    type: "vnet"
    name: "randn"
    dependencies:
      - "tn_init"
    input:
      one_vnet_first_ip: "10.10.10.1"
      one_vnet_netmask: "255.255.255.0"
      one_vnet_address_size: 254
      one_vnet_gw: "10.10.10.1"
      one_vnet_dns: "1.1.1.1"
  open5gs_vm-core:
    type: open5gs_vm
    name: core
    dependencies:
      - tn_init
      - vnet-randn
    input:
      one_open5gs_vm_size: "small"
      one_open5gs_vm_networks:
        - tn_vxlan
        - vnet-randn
      one_open5gs_vm_ue_subnet: "10.45.0.0/16"
      one_open5gs_vm_mcc: "001"
      one_open5gs_vm_mnc: "01"
      one_open5gs_vm_msin: "0000000001"
      one_open5gs_vm_key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      one_open5gs_vm_opc: "E8ED289DEBA952E4283B54E88E6183CA"
      one_open5gs_vm_apn: "internet"
      one_open5gs_vm_tac: 200
      one_open5gs_vm_s_nssai_sst: 1
      one_open5gs_vm_s_nssai_sd: "000001"
      one_open5gs_vm_amf_ip: "10.10.10.200"
      one_open5gs_vm_upf_ip: "10.10.10.201"
      one_open5gs_vm_ue_count: 20
  loadcore_agent-dn:
    type: "loadcore_agent"
    name: "dn"
    input:
      one_loadcore_agent_networks:
        - "tn_vxlan"
        - "vnet-randn"
        - "vnet-randn"
  loadcore_agent-gnb:
    type: "loadcore_agent"
    name: "gnb"
    input:
      one_loadcore_agent_networks:
        - "tn_vxlan"
        - "vnet-randn"
        - "vnet-randn"
        - "vnet-randn"
```

The required fixes are:

- In OpenNebula, the network `vnet-randn` should show that IPs 10.10.10.200 and 10.10.10.201 are occupied.
- Update this value in the corresponding YAML file for Open5GS.

Don't know if any more specific steps are needed.

**Comment by bjoern-r** [comment]
I'm not aware if OpenNebula could assigne multiple ip addresses to an single interface.

**Comment by CarlosAndreo** [comment]
Let's follow this approach

| Network Number | Used For       | Notes                                                 |
|----------------|----------------|-------------------------------------------------------|
| 1 (eth0)       | Management     | Used as fallback for N2 and N3 if the only interface |
| 2 (eth1)       | N2 (AMF)       | Used as fallback for N3 if no N3 network specified   |
| 3 (eth2)       | N3 (UPF)       |                                                       |

Trial network descriptor
```yaml
trial_network:

  tn_init:
    type: "tn_init"
    dependencies: []
    input: {}
  vnet-n2:
    type: "vnet"
    name: "n2"
    dependencies:
      - "tn_init"
    input:
      one_vnet_first_ip: "10.10.10.1"
      one_vnet_netmask: "255.255.255.0"
      one_vnet_address_size: 254
      one_vnet_gw: "10.10.10.1"
      one_vnet_dns: "1.1.1.1"
  # vnet-n3:
  #   type: "vnet"
  #   name: "n3"
  #   dependencies:
  #     - "tn_init"
  #   input:
  #     one_vnet_first_ip: "10.10.11.1"
  #     one_vnet_netmask: "255.255.255.0"
  #     one_vnet_address_size: 254
  #     one_vnet_gw: "10.10.11.1"
  #     one_vnet_dns: "1.1.1.1"
  open5gs_vm-core:
    type: "open5gs_vm"
    name: "core"
    dependencies:
      - "tn_init"
      - "vnet-n2"
      # - "vnet-n3"
    input:
      one_open5gs_vm_size: "small"
      one_open5gs_vm_external_vnet: "tn_vxlan"
      one_open5gs_vm_internal_vnet: 
        - "vnet-n2"  # network used for n2 and n3 (when list length =1)
        #- "vnet-n3" # optional network used for n3
      one_open5gs_vm_ue_subnet: "10.45.0.0/16"
      one_open5gs_vm_mcc: "001"
      one_open5gs_vm_mnc: "01"
      one_open5gs_vm_msin: "0000000001"
      one_open5gs_vm_key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
      one_open5gs_vm_opc: "E8ED289DEBA952E4283B54E88E6183CA"
      one_open5gs_vm_apn: "internet"
      one_open5gs_vm_tac: 200
      one_open5gs_vm_s_nssai_sst: 1
      one_open5gs_vm_s_nssai_sd: "000001"
      one_open5gs_vm_amf_ip: "10.10.10.200"
      one_open5gs_vm_upf_ip: "10.10.11.201"
      one_open5gs_vm_ue_count: 20
  loadcore_agent-dn:
    type: "loadcore_agent"
    name: "dn"
    input:
      one_loadcore_agent_networks:
        - "tn_vxlan"
        - "vnet-n2"
  loadcore_agent-gnb:
    type: "loadcore_agent"
    name: "gnb"
    input:
      one_loadcore_agent_networks:
        - "tn_vxlan"
        - "vnet-n2"
        - "vnet-n2"
```
