### ISSUE TITLE
Suggestion to change the appliance metadata field

### ISSUE THREAD

**Issue by CarlosAndreo** [6G-SANDBOX/6G-Library#70]
I am developing the 6G-SANDBOX toolkit installer and would like to introduce what I consider an improvement.

Currently in the public.yaml file located in the .tnlcm directory there is a field inside **metadata** that is **appliance**. This field contains the url to the appliance, which makes the development of the toolkit difficult.

As a possible solution I propose the following:

```yaml
metadata:
	appliance: 
		appliance_name: "UERANSIM"
		appliance_versions:
			- v0.0.0
			- v0.1.0
			- ...
```

Where:
- **appliance_name** must be the same name with which the appliance appears in the marketplace.
- **appliance_versions** list with the different versions of the appliance

We should follow a name format for the appliance names.
